# Generated by Django 4.2.6 on 2023-11-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogdevice',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digitaldevice',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartdevice',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
